### ISSUE TITLE
Latest release not working throws System.IO.IOException

### ISSUE THREAD

**Issue by Mini-Placzek** [Nenkai/GTToolsSharp#4]
Hi I just came across your project because I need to extract my GT6 volume. I downloaded the latest release [5.0.0](https://github.com/Nenkai/GTToolsSharp/releases/tag/5.0.0) and tried unpacking the GT6.VOL using `GTToolsSharp.exe unpack -i GT.VOL -o extracted`. It generated the default keys.json and on the second time running this command I'll get this exception every time: 

`...GTToolsSharp>GTToolsSharp.exe unpack -i GT.VOL -o extracted
-- GTToolsSharp 5.0.0 - (c) Nenkai#9075, ported from flatz's gttool --

Unhandled exception. System.TypeInitializationException: The type initializer for 'GTToolsSharp.Program' threw an exception.
 ---> System.IO.IOException: The process cannot access the file 'D:\Save\PS3\Tools\GTToolsSharp\log.txt' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at GTToolsSharp.Program..cctor()
   --- End of inner exception stack trace ---
   at GTToolsSharp.Program.Unpack(UnpackVerbs options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult 1 result, Action 1 action)
   at GTToolsSharp.Program.Main(String[] args)
   at GTToolsSharp.Program.<Main>(String[] args)`
  
Checked if any other process is conflicting but couldn't find anything. Tried the same procedure with the previous release [4.0.6](https://github.com/Nenkai/GTToolsSharp/releases/tag/4.0.6) and it worked just fine got all the files extracted. Btw I'm using the EU Version of GT6 if that matters (BCES01893).
Just wanted to let you know and thank you for your work.

**Comment by Nenkai** [comment]
Should be fixed with 20cd66d20df3226370bb9595175e3152d4ecbbcd (5.1.0)
Thanks for the report.
