### ISSUE TITLE
Problem while packing

### ISSUE THREAD

**Issue by KuRuMaA** [Nenkai/GTToolsSharp#5]
I try to pack the GT6 Spec II Mod with only a custom event added, I would try to pack it again and it would show me the following error:
Unhandled exception. System.TypeInitializationException: The type initializer fo
r 'GTToolsSharp.Program' threw an exception.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\DeezNuts\
Desktop\Test\log.txt' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share,
FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append
, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at GTToolsSharp.Program..cctor()
   --- End of inner exception stack trace ---
   at GTToolsSharp.Program.Pack(PackVerbs options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Ac
tion`1 action)
   at GTToolsSharp.Program.Main(String[] args)
   at GTToolsSharp.Program.<Main>(String[] args)

I would like to know the solution for the problem

**Comment by Nenkai** [comment]
Thought I fixed this issue in another commit but it was still present somewhere else.
Fixed with 5.1.1.
